import xml.etree.ElementTree as ET
import sys
#ET.register_namespace('',"http://pds.nasa.gov/pds4/pds/v1")
tree = ET.parse('context.xml')
root = tree.getroot()
#target_id = root.
times = ["2014-01-23 00:34:23.234","next time period"] #<< can be autogenerated?
#for element in tree.iter():
#for time in root.iter("./*"):
#    time.text = "can set this to be predetermined from an array of values"
#
#write a comparison function that makes sure that time has to be later
sample = root.findall("./Time_Coordinates/*")
for some in sample:
    some.text = "aaaaaaaaa"
#print(sample)
#print (type(root)) # Element
#print (type(tree)) # ElementTree
#for target in 
#context = tree.findall('Context_Area')
#print (context)
#figure out how to get subtree elements
tree.write(sys.stdout, "unicode")
